version: "2.1"
volumes:
  jupyter:
services:
  ad-block:
    build:
      context: .
    restart: always
    privileged: true
    #image: ghcr.io/rcooke-warwick/hardware-debug-block:latest
    volumes:
      - "jupyter:/data"
    ports:
      - "80:8888"
