version: "2.1"
volumes:
  jupyter:
services:
  analog-discovery-block:
    restart: always
    build: .
    privileged: true
    volumes:
      - "jupyter:/data"
    ports:
      - "8080:5900"
      - "80:8888"
    environment:
      - PASSWORD=default
